config/routes.rb
Rails.application.routes.draw do
  resources :customers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
	 validates :full_name, presence: true
	 validates :email, presence: true, uniqueness: true
	 validates :contact_number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController  < ApplicationController
	def index
		@customers = Customer.all
	end

	def show
		@customer = Customer.find(params[:id])
	end

	def new
		@customer = Customer.new
	end

	def create
		customer = Customer.new(customer_params) 
        stripe_customer = StripeService.new.find_or_create_stripe_customer(customer)
        
        puts "found stripe customer id: #{stripe_customer}"
        if stripe_customer.present? && customer.present?
            customer.save
        	redirect_to customer
        else
        	render :new, status: :unprocessable_entity
        end

	end

	private
	def customer_params
      params.require(:customer).permit(:full_name, :email, :contact_number)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customers/index.html.erb
<style>
  
  table, th, td{
    border: 1px solid black;
    border-collapse: collapse;
  }
</style>

<table>
	<thead>
		<tr>
			<th>Full_Name</th>
			<th>Email</th>
			<th>Contact_Number</th>
		</tr>
	</thead>

	<tbody>
		<% @customers.each do |customer| %>
		<tr>
			<td><%= customer.full_name%></td>
			<td><%= customer.email %></td>
			<td><%= customer.contact_number %></td>
			<td><%= link_to 'Show', customer_path(customer) %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<br>
<%= link_to 'Create New customer', new_customer_path(@customer) %>

app/views/customers/new.html.erb
<%= form_with model: @customer do |form| %>
  <div>
    <%= form.label :Full_Name %><br>
    <%= form.text_field :full_name %>
  </div>

  <br>
  <div>
    <%= form.label :Email %><br>
    <%= form.text_field :email %>
  </div>

  <br>
  <div>
    <%= form.label :Contact_Number %><br>
    <%= form.text_field :contact_number %>
  </div>

  <br>

  <div>
    <%= form.submit %>
  </div>

  <br>
  <% end %>

  <%= link_to 'Back to Customer', customers_path(@customer) %>

app/views/customers/show.html.erb
<h1> customer details </h1>
  

Customer_Name: <%= @customer.full_name %><br>
Email: <%= @customer.email %></br>
Phone_Number: <%= @customer.contact_number %></br><br>
	

<%= link_to 'back_to_customer_page', customers_path(@customer) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StripeDemoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>